# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prt < Formula
  desc "GitHub PR Tracker - Aggregate PR status across multiple repositories"
  homepage "https://github.com/ChrisEdwards/pr-tracker"
  version "0.3.0"
  license "MIT"

  depends_on "gh" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.3.0/prt_0.3.0_darwin_amd64.tar.gz"
      sha256 "0bb1c86e0ed26a1d759c5db8eb69d65f59b93f31576c9fa676a25ae80b797080"

      def install
        bin.install "prt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.3.0/prt_0.3.0_darwin_arm64.tar.gz"
      sha256 "c415347d1150dbe8f199ee40bf7ed5e087da78338dc98bad132605cb8063c9b7"

      def install
        bin.install "prt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.3.0/prt_0.3.0_linux_amd64.tar.gz"
      sha256 "009592217eb3f858207cdd44b487adc62fec1e65157105fa4042997c6d520244"
      def install
        bin.install "prt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.3.0/prt_0.3.0_linux_arm64.tar.gz"
      sha256 "e6e3217d0c0190d46073e6b9aaac95f91b04ccc905733b1a8705746d71b44bc8"
      def install
        bin.install "prt"
      end
    end
  end

  def caveats
    <<~EOS
      PRT requires the GitHub CLI (gh) to be installed and authenticated.

      If not already installed:
        brew install gh

      Then authenticate:
        gh auth login

      Run `prt` to start the setup wizard.
    EOS
  end

  test do
    system "#{bin}/prt", "--version"
  end
end
