# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prt < Formula
  desc "GitHub PR Tracker - Aggregate PR status across multiple repositories"
  homepage "https://github.com/ChrisEdwards/pr-tracker"
  version "0.4.0"
  license "MIT"

  depends_on "gh" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.4.0/prt_0.4.0_darwin_amd64.tar.gz"
      sha256 "fa81b077f9dc7c4aeab936ceac51bf784603a5d5101f37df4620f3e3e2c02e74"

      def install
        bin.install "prt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.4.0/prt_0.4.0_darwin_arm64.tar.gz"
      sha256 "c73447274f5b9cab51faf53c40f4bb9f1cc40100b45e47782ace5416ffaa922d"

      def install
        bin.install "prt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.4.0/prt_0.4.0_linux_amd64.tar.gz"
      sha256 "6a832eee21e3c24a1227ad65d359c298e5d69decfebf6239a770b6c173bc64a1"
      def install
        bin.install "prt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.4.0/prt_0.4.0_linux_arm64.tar.gz"
      sha256 "57782889ae1a7d588d7ff917aac3709f84ca0e8e77e9dcc64f8f3f1e8ea64f7d"
      def install
        bin.install "prt"
      end
    end
  end

  def caveats
    <<~EOS
      PRT requires the GitHub CLI (gh) to be installed and authenticated.

      If not already installed:
        brew install gh

      Then authenticate:
        gh auth login

      Run `prt` to start the setup wizard.
    EOS
  end

  test do
    system "#{bin}/prt", "--version"
  end
end
