# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prt < Formula
  desc "GitHub PR Tracker - Aggregate PR status across multiple repositories"
  homepage "https://github.com/ChrisEdwards/pr-tracker"
  version "0.5.0"
  license "MIT"

  depends_on "gh" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.5.0/prt_0.5.0_darwin_amd64.tar.gz"
      sha256 "6060ccb3fcb03e7c445b2ef49f4c8af1cbb7f0877cd4f1929b45f0dabb89f0c3"

      def install
        bin.install "prt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.5.0/prt_0.5.0_darwin_arm64.tar.gz"
      sha256 "8b95cfa84c389bb918c75a7bf7070dc923ada923e50885592b9ac34a5e0c041f"

      def install
        bin.install "prt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.5.0/prt_0.5.0_linux_amd64.tar.gz"
      sha256 "0453149a652ae2ef99ff6470404c549b67bb5bd54456f265cc62aaa4a5dc7ad8"
      def install
        bin.install "prt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisEdwards/pr-tracker/releases/download/v0.5.0/prt_0.5.0_linux_arm64.tar.gz"
      sha256 "4fd6778dd266041d5613ec27032409533a1d5458d312d14c4a70aedfe7e59977"
      def install
        bin.install "prt"
      end
    end
  end

  def caveats
    <<~EOS
      PRT requires the GitHub CLI (gh) to be installed and authenticated.

      If not already installed:
        brew install gh

      Then authenticate:
        gh auth login

      Run `prt` to start the setup wizard.
    EOS
  end

  test do
    system "#{bin}/prt", "--version"
  end
end
